gpt4o_openai_api_key = "YOUR API KEY"
org_id = "YOUR API KEY"
gpt4_api_key = "YOUR API KEY"
gpt4_api_base = "YOUR API KEY"
gpt4_api_version = "YOUR API KEY"
hf_api_key = "YOUR API KEY"
google_api_key = "YOUR API KEY"